/*
 * THIS IS AUTOGENERATED FILE 
*/

/*----------------------------------------------------------------------*/

#include <wchar.h>

/*----------------------------------------------------------------------*/

const size_t xwui_strings_en_us_strings_count = 9;

/* localization strings */
const char* xwui_strings_en_us_strings[] = {
    "Add",
    "Back",
    "Copy",
    "Cut",
    "Delete",
    "Forward",
    "Join",
    "Paste",
    "View"
};

/* localization string values */
const wchar_t* xwui_strings_en_us_values[] = {
    L"",
    L"",
    L"",
    L"",
    L"",
    L"",
    L"",
    L"",
    L""
};

/*----------------------------------------------------------------------*/
