/*
 * THIS IS AUTOGENERATED FILE 
*/

/*----------------------------------------------------------------------*/

#include <wchar.h>

/*----------------------------------------------------------------------*/

const size_t xwui_strings_ru_ru_strings_count = 9;

/* localization strings */
const char* xwui_strings_ru_ru_strings[] = {
    "Add",
    "Back",
    "Copy",
    "Cut",
    "Delete",
    "Forward",
    "Join",
    "Paste",
    "View"
};

/* localization string values */
const char* xwui_strings_ru_ru_values[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
};

/*----------------------------------------------------------------------*/
